<?php

namespace Modules\Cargo\Database\Seeders;

use App\Models\User;
use Illuminate\Database\Seeder;
use Modules\Bar\Models\Bar;
use Modules\Cargo\Models\Cargo;
use Modules\Cargo\Models\CargoLastState;
use Modules\Item\Models\Item;
use Modules\Stocktake\Models\Scan;
use Modules\Stocktake\Models\Stocktake;
use Modules\Stocktake\Models\StocktakeUser;

class CargoDatabaseSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $cargos = [
            [
                'name' => 'Vodka DOUBLE CROSS 0.7l 40%',
                'brand' => 'DOUBLE CROSS',
                'type' => 0,
                'volume' => 700,
                'alcohol' => 40,
                'ean' => '8586005331605',
                'weight_full' => 2040,
                'weight_empty' => 1340,
                'weight_tolerance' => 10,
                'original' => 0,
                'duplicate' => 0,
            ],
            [
                'name' => 'Hardys Noces de Perle 30y,0,75l, 40% darè.bal.',
                'brand' => null,
                'type' => 0,
                'volume' => 750,
                'alcohol' => 40,
                'ean' => '3104051156048',
                'weight_full' => null,
                'weight_empty' => null,
                'weight_tolerance' => null,
                'original' => 0,
                'duplicate' => 0,
            ],
            [
                'name' => 'Whisky Murray McDavid Tobermory 1995, 15yo',
                'brand' => null,
                'type' => 0,
                'volume' => 700,
                'alcohol' => 46,
                'ean' => '618105005501',
                'weight_full' => null,
                'weight_empty' => null,
                'weight_tolerance' => null,
                'original' => 0,
                'duplicate' => 0,
            ],
            [
                'name' => 'WHITE HORSE',
                'brand' => null,
                'type' => 0,
                'volume' => 1000,
                'alcohol' => 40,
                'ean' => '5000265001335',
                'weight_full' => null,
                'weight_empty' => null,
                'weight_tolerance' => null,
                'original' => 0,
                'duplicate' => 0,
            ],
            [
                'name' => 'BATHTUB GIN NAVY STRENGTH 57% 0,7L',
                'brand' => null,
                'type' => 0,
                'volume' => 700,
                'alcohol' => 57,
                'ean' => '5052598010348',
                'weight_full' => null,
                'weight_empty' => null,
                'weight_tolerance' => null,
                'original' => 0,
                'duplicate' => 0,
            ],
            [
                'name' => 'Transcontinental Rum Line Venezuela 2006 0,7l 60,9',
                'brand' => null,
                'type' => 0,
                'volume' => 700,
                'alcohol' => 60.9,
                'ean' => '3700597343760',
                'weight_full' => null,
                'weight_empty' => null,
                'weight_tolerance' => null,
                'original' => 0,
                'duplicate' => 0,
            ],
            [
                'name' => 'Don Q Anejo 40% 70cl',
                'brand' => null,
                'type' => 0,
                'volume' => 700,
                'alcohol' => 40,
                'ean' => '82301700551',
                'weight_full' => null,
                'weight_empty' => null,
                'weight_tolerance' => null,
                'original' => 0,
                'duplicate' => 0,
            ],
            [
                'name' => 'Likér kokosový  28% 0,5L',
                'brand' => null,
                'type' => 0,
                'volume' => 500,
                'alcohol' => 28,
                'ean' => '8586008391132',
                'weight_full' => null,
                'weight_empty' => null,
                'weight_tolerance' => null,
                'original' => 0,
                'duplicate' => 0,
            ],
            [
                'name' => 'Hardys Noces de Diamant 60y 0,75 40% darèek',
                'brand' => null,
                'type' => 0,
                'volume' => 750,
                'alcohol' => 40,
                'ean' => '3104051156055',
                'weight_full' => null,
                'weight_empty' => null,
                'weight_tolerance' => null,
                'original' => 0,
                'duplicate' => 0,
            ],
            [
                'name' => 'Pálenka Marhulovica',
                'brand' => null,
                'type' => 0,
                'volume' => 100,
                'alcohol' => 52,
                'ean' => '8588003111203',
                'weight_full' => null,
                'weight_empty' => null,
                'weight_tolerance' => null,
                'original' => 0,
                'duplicate' => 0,
            ],
            [
                'name' => 'Futbalová lopta 0,35l 40%',
                'brand' => null,
                'type' => 0,
                'volume' => 350,
                'alcohol' => 40,
                'ean' => '8592567001344',
                'weight_full' => null,
                'weight_empty' => null,
                'weight_tolerance' => null,
                'original' => 0,
                'duplicate' => 0,
            ],
            [
                'name' => 'DON PAPA RUM GIFT BOX',
                'brand' => null,
                'type' => 0,
                'volume' => 700,
                'alcohol' => 40,
                'ean' => '.480901515701',
                'weight_full' => null,
                'weight_empty' => null,
                'weight_tolerance' => null,
                'original' => 0,
                'duplicate' => 0,
            ],
            [
                'name' => 'CREAM GIN 0,7 43,8% *',
                'brand' => null,
                'type' => 0,
                'volume' => 700,
                'alcohol' => 43.8,
                'ean' => '5052598010355',
                'weight_full' => null,
                'weight_empty' => null,
                'weight_tolerance' => null,
                'original' => 0,
                'duplicate' => 0,
            ],
            [
                'name' => 'Habitation Velier Worthy Park WPL 2007',
                'brand' => null,
                'type' => 0,
                'volume' => 700,
                'alcohol' => 59,
                'ean' => '3700597351130',
                'weight_full' => null,
                'weight_empty' => null,
                'weight_tolerance' => null,
                'original' => 0,
                'duplicate' => 0,
            ],
            [
                'name' => 'Rumquila Red Eye Louies',
                'brand' => null,
                'type' => 0,
                'volume' => 700,
                'alcohol' => 40,
                'ean' => '823586000116',
                'weight_full' => null,
                'weight_empty' => null,
                'weight_tolerance' => null,
                'original' => 0,
                'duplicate' => 0,
            ],
            [
                'name' => 'Likér kiwi 28% 0,5L',
                'brand' => null,
                'type' => 0,
                'volume' => 500,
                'alcohol' => 28,
                'ean' => '8586008391149',
                'weight_full' => null,
                'weight_empty' => null,
                'weight_tolerance' => null,
                'original' => 0,
                'duplicate' => 0,
            ],
            [
                'name' => 'A Wh.White Horse Gold E.1890 43%1,0',
                'brand' => null,
                'type' => 0,
                'volume' => 1000,
                'alcohol' => 43,
                'ean' => '5000265101417',
                'weight_full' => null,
                'weight_empty' => null,
                'weight_tolerance' => null,
                'original' => 0,
                'duplicate' => 0,
            ],
            [
                'name' => 'Whisky Murray McDavid Bunnahabhain 1997, 13yo',
                'brand' => null,
                'type' => 0,
                'volume' => 700,
                'alcohol' => 46,
                'ean' => '618105005525',
                'weight_full' => null,
                'weight_empty' => null,
                'weight_tolerance' => null,
                'original' => 0,
                'duplicate' => 0,
            ],
            [
                'name' => 'C-Hardy-7-Perfection Water.Eau.Voda-41%-dec-lgb',
                'brand' => null,
                'type' => 0,
                'volume' => 750,
                'alcohol' => 41,
                'ean' => '3104051156079',
                'weight_full' => null,
                'weight_empty' => null,
                'weight_tolerance' => null,
                'original' => 0,
                'duplicate' => 0,
            ],
            [
                'name' => 'Bathtub Sloe Gin 0,5l, 33,8%',
                'brand' => null,
                'type' => 0,
                'volume' => 500,
                'alcohol' => 33.8,
                'ean' => '5052598048310',
                'weight_full' => null,
                'weight_empty' => null,
                'weight_tolerance' => null,
                'original' => 0,
                'duplicate' => 0,
            ],
            [
                'name' => 'F¾aa s prstienkami 0.35L',
                'brand' => null,
                'type' => 0,
                'volume' => 350,
                'alcohol' => 40,
                'ean' => '8592567001351',
                'weight_full' => null,
                'weight_empty' => null,
                'weight_tolerance' => null,
                'original' => 0,
                'duplicate' => 0,
            ],
            [
                'name' => 'Habitation Velier Savanna Herr White 0,7l  62,5%',
                'brand' => null,
                'type' => 0,
                'volume' => 700,
                'alcohol' => 62.5,
                'ean' => '3700597351147',
                'weight_full' => null,
                'weight_empty' => null,
                'weight_tolerance' => null,
                'original' => 0,
                'duplicate' => 0,
            ],
            [
                'name' => 'Pálenka Hrukovica',
                'brand' => null,
                'type' => 0,
                'volume' => 100,
                'alcohol' => 52,
                'ean' => '8588003111210',
                'weight_full' => null,
                'weight_empty' => null,
                'weight_tolerance' => null,
                'original' => 0,
                'duplicate' => 0,
            ],
            [
                'name' => 'VODKA TOWN PEACH 0.7L 21%',
                'brand' => null,
                'type' => 0,
                'volume' => 700,
                'alcohol' => 21,
                'ean' => '8586008391255',
                'weight_full' => null,
                'weight_empty' => null,
                'weight_tolerance' => null,
                'original' => 0,
                'duplicate' => 0,
            ],
            [
                'name' => 'Smirnoff mini 0,05l',
                'brand' => null,
                'type' => 0,
                'volume' => 50,
                'alcohol' => 40,
                'ean' => '82472016',
                'weight_full' => null,
                'weight_empty' => null,
                'weight_tolerance' => null,
                'original' => 0,
                'duplicate' => 0,
            ],
            [
                'name' => 'Ciroc Vodka Moschino Desing Edition',
                'brand' => null,
                'type' => 0,
                'volume' => 700,
                'alcohol' => 40,
                'ean' => '5000265101790',
                'weight_full' => null,
                'weight_empty' => null,
                'weight_tolerance' => null,
                'original' => 0,
                'duplicate' => 0,
            ],
            [
                'name' => 'Octomore 4.1 Comus',
                'brand' => null,
                'type' => 0,
                'volume' => 700,
                'alcohol' => 61,
                'ean' => '618105005785',
                'weight_full' => null,
                'weight_empty' => null,
                'weight_tolerance' => null,
                'original' => 0,
                'duplicate' => 0,
            ],
            [
                'name' => 'Hardy Noces de Perle Decanter 0.70L GB',
                'brand' => null,
                'type' => 0,
                'volume' => 700,
                'alcohol' => 40,
                'ean' => '3104051156178',
                'weight_full' => null,
                'weight_empty' => null,
                'weight_tolerance' => null,
                'original' => 0,
                'duplicate' => 0,
            ],
            [
                'name' => 'Habitation Velier Last Ward 2009 9y 0,7l 59% GB',
                'brand' => null,
                'type' => 0,
                'volume' => 700,
                'alcohol' => 59,
                'ean' => '3700597351154',
                'weight_full' => null,
                'weight_empty' => null,
                'weight_tolerance' => null,
                'original' => 0,
                'duplicate' => 0,
            ],
            [
                'name' => 'Rumbullion XO 15YO 46,2% 0,5l',
                'brand' => null,
                'type' => 0,
                'volume' => 500,
                'alcohol' => 46.2,
                'ean' => '5052598054151',
                'weight_full' => null,
                'weight_empty' => null,
                'weight_tolerance' => null,
                'original' => 0,
                'duplicate' => 0,
            ],
        ];

        $eans = [];
        foreach ($cargos as $cargo) {
            $eans[] = $cargo['ean'];
            Cargo::create($cargo);
        }
        for($i = 0; $i <= 29; $i++){
            $cargoLastState = [
                'user_id' => User::first()->id,
                'bar_id' => Bar::first()->id,
                'cargo_id' => rand(1,30),
                'type' => 1,
                'last_stocktake' => rand(100,1000),
                'product_key_supplier' => null,
                'weight_last_stocktake' => rand(100,1000),
                'full_pack_last_stocktake' => rand(0,5),
                'weight_count' => rand(100,2000),
            ];
            CargoLastState::create($cargoLastState);
        }

        for($i = 0; $i <= 29; $i++){
            $items = [
                'user_id' => User::first()->id,
                'bar_id' => Bar::first()->id,
                'type' => 1,
                'cargo_id' => rand(1,30),
                'last_stocktake' => rand(100,1000),
                'product_key_supplier' => null,
                'weight_last_stocktake' => rand(100,1000),
                'full_pack_last_stocktake' => rand(0,5),
            ];
            Item::create($items);
        }

        StocktakeUser::create([
            'name' => '',
            'surname' => 'admin',
            'permissions' => '',
            'password' => 'a665a45920422f9d417e4867efdc4fb8a04a1f3fff1fa07e998e86f7f7a27ae3',
            'token' => 'edcd224d4b247032f6007dc14b819da34a124b6207e32fe465e2d326aa439ccd',
            'api' => 156,
            'bar_id' => 1,
            'user_id' => 1,
            'stocktake_id' => 1,
            'mine' => 1,
        ]);


        Stocktake::create([
            'user_id' => User::first()->id,
            'bar_id' => Bar::first()->id,
            'mine_user' => 1,
            'users' => json_encode([]),
            'api' => 'aPEpcrCURol9U4fz',
            'password' => 'a665a45920422f9d417e4867efdc4fb8a04a1f3fff1fa07e998e86f7f7a27ae3',
            'open' => 1,
        ]);


        for($i = 0; $i <= 29; $i++){
            $scans = [
                'ean' => $eans[$i],
                'type' => 1,
                'update_data' => ($i<2)? 0 : 1 ,
                'stocktake_user_id' => 1,
                'stocktake_id' => 1,
                'api' => 156,
                'weight' => 1600,
                'full_pack' => rand(0,5),
                'add_full_pack' => rand(10,20),
                'expire' => 23123891912,
            ];
            Scan::create($scans);
        }
    }
}
